package com.revature.portal.util.exceptions;

public class DataSourceException extends RuntimeException {
    public DataSourceException(String s, Throwable cause) {
        super(s, cause);
    }
}
